# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14c86f9ddd092af15f3106b9dbb3b86eee3171efb9adf2f145dd37c3aeed32ed11482075cb67738f9bfc547dce8f9c6306ff464f352dcaadfbabc65edd98bc2b

test:
  secret_key_base: 16174f2a034fd8c59cc8c42b549822afaeb1fe4c8fcbcbad416d4b4afa01c18fd5eb56df3a7426ea4720e6ca195ecdf1bb137b2cfe795af890604d722c19a082

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
